### PR TITLE
[Number3]added login function

### PR DESCRIPTION
**Pull request by KoutarouTakayama**
_**Commands to run**_
-php artisan migrate

_**Preconditions**_
-User can input email-address and password on login page.

_**Expected outputs**_
-If the data is on the database, dashboard page is displayed.
-User can't go bask to login page and register page without logout.
-After logout, users can go back to dashboard but **maybe users can't do anything there. I'm going to make it sure and fix it next PR.**

_**asana URL**_
-https://app.asana.com/0/1107951271303646/1108355718269625

_**memo**_
-In some files I rewrote "/home" into "/dashboard" because after login, user would go to "/home" with former PR but I wanted to set dashboard page in "/dashboard" and I want users to use the dashboard page as home page. That's why I changed them. 
-In Controller file, I just added view function to display dashboard page.
-I created layout file and simple dashboard page.
-I added "word" column in words table. I just had forgotten to add this in former PR.

### CODE REVIEW

**Comment by jeremiahC** [comment]
@KoutarouTakayama where is the login functionality?

**Comment by KoutarouTakayama** [comment]
Actually, login functionality had been implemented on former PR because I just changed files which were made by "php artisan make:auth". I just changed pages which is displayed after login. If you want me to make login functionality by myself, I'm going to do so.

**Review by jeremiahC — COMMENTED** [review]
Not good point

* I can still login even though i'm not yet registered as user

**Comment by KoutarouTakayama** [comment]
- I changed session settings. If browser is closed, the session will be stopped and user cannot go to dashboard page again without login.
- I realized /home isn't needed so I deleted it.
- I added logout functionality for being able to logout. Logout functionality isn't included in any tasks so I decided to add in this PR. If it's not good, I'm going to make new task for logout functionality.

**Review by jeremiahC — APPROVED** [review]

**Pull request merged**
